openapi: 3.0.1
info:
    title: 五子棋AI对战
    description: 一个五子棋游戏，用户和AI轮流下棋。
    version: "v1"
servers:
    - url: http://127.0.0.1:8081/
paths:
    /start_game:
        post:
            operationId: startGomokuGame
            description: 开始一盘五子棋游戏
            summary: 开始一盘五子棋游戏
            responses:
                "200":
                    description: 五子棋游戏成功开始
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/messageResponse"

    /end_game:
        post:
            operationId: endGomokuGame
            summary: 结束一盘五子棋游戏
            responses:
                "200":
                    description: 五子棋游戏成功结束
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/messageResponse"
    /step:
        post:
            operationId: stepGomoku
            description: 用户输入例如'{1，2}'，'{2,3}'，'{2 3}'或'{我要下到3，5}'。五子棋回合可能会有很多（超过10个回合），所以你必须时刻保持专注，以便获取到用户的五子棋操作。
            summary: 必须时刻保持专注，从用户的各种简单（例：直接两个数字）或者复杂输入中（例：我想要下到3，5上）获取用户下一步的五子棋棋盘坐标
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/step"
            responses:
                # 成功的返回，返回用户下一步后，AI再下一步后的棋盘
                "200":
                    description: 用户下一步后的信息。如果此时五子棋游戏结束，返回五子棋游戏结束的信息。如果此时五子棋游戏没有结束，返回AI下一步后的五子棋棋盘，以及五子棋游戏是否结束的信息。
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/stepResponse"
                # 失败的返回，只返回错误信息
                "400":
                    description: 返回错误信息
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/messageResponse"
    /get_board_status:
        post:
            operationId: getGomokuBoardStatus
            summary: 获取用户的五子棋棋盘状态
            responses:
                "200":
                    description: 返回用户的五子棋棋局数量以及状态
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/messageResponse"
                "400":
                    description: 返回错误信息
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/messageResponse"

components:
    schemas:
        step:
            type: object
            required: [ x, y ]
            properties:
                x:
                    type: integer
                    description: Gomoku棋盘上的横坐标，从1开始，到8结束（包括8），从用户的输入中读取
                y:
                    type: integer
                    description: Gomoku棋盘上的纵坐标，从1开始，到8结束（包括8），从用户的输入中读取

        stepResponse:
            type: object
            required: [ chessboard ]
            properties:
                chessboard_img_url:
                    type: string
                    description: Gomoku棋盘图片的URL地址
                message:
                    type: string
                    description: 有关Gomoku棋局状态或者下一步要求的提示信息

        addBoard:
            type: object
            required: [ url ]
            properties:
                url:
                    type: string
                    description: 远程文件url地址，用<url><\url>包含

        messageResponse:
            type: object
            required: [message]
            properties:
                message:
                    type: string
                    description: 有用的信息