openapi: 3.0.1
info:
    title: 一步一言
    description: 一步一言是一个五子棋游戏，用户和AI轮流下棋。
    version: "v1"
servers:
    - url: http://47.113.230.250:8088/
paths:
    /start_game:
        post:
            operationId: startGame
            description: 开始一盘五子棋游戏
            summary: 开始一盘五子棋游戏
            responses:
                "200":
                    description: 游戏成功开始
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/messageResponse"

    /end_game:
        post:
            operationId: endGame
            summary: 结束一盘五子棋游戏
            responses:
                "200":
                    description: 游戏成功结束
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/messageResponse"
    /step:
        post:
            operationId: step
            description: 用户下一步棋，用户的输入可能为：{1，2}--代表x=1，y=2\n{2,3}---代表x=2，y=3\n{2 3}---代表x=2，y=3\n{我要下到3，5}---代表x=3，y=5
            summary: 从用户的各种简单（例：直接两个数字）或者复杂输入中（例：我想要下到3，5上）获取用户下一步的棋盘坐标，返回AI下一步后的棋盘
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/step"
            responses:
                # 成功的返回，返回用户下一步后，AI再下一步后的棋盘
                "200":
                    description: 用户下一步后的信息。如果此时游戏结束，返回游戏结束的信息。如果此时游戏没有结束，返回AI下一步后的棋盘，以及游戏是否结束的信息。
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/stepResponse"
                # 失败的返回，只返回错误信息
                "400":
                    description: 返回错误信息
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/messageResponse"


components:
    schemas:
        step:
            type: object
            required: [ x, y ]
            properties:
                x:
                    type: integer
                    description: 棋盘上的横坐标，从1开始，到8结束（包括8），从用户的输入中读取
                y:
                    type: integer
                    description: 棋盘上的纵坐标，从1开始，到8结束（包括8），从用户的输入中读取

        stepResponse:
            type: object
            required: [ board ]
            properties:
                board:
                    type: array
                    items:
                        type: array
                        items:
                            type: string
                    description: 棋盘的Markdown表示，需要不加更改的仔细保持原样输出Markdown格式

        addBoard:
            type: object
            required: [ url ]
            properties:
                url:
                    type: string
                    description: 远程文件url地址，用<url><\url>包含

        messageResponse:
            type: object
            required: [message]
            properties:
                message:
                    type: string
                    description: 有用的信息