openapi: 3.0.1
info:
    title: 棋盘_0206
    description: 读取文件中的棋盘，获取下一步棋的最佳下法
    version: "v1"
servers:
    - url: http://127.0.0.1:8081
paths:
    /start_game:
        post:
            operationId: startGame
            summary: 开始一盘五子棋游戏
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/addBoard"
            responses:
                "200":
                    description: 游戏成功开始
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/messageResponse"

    /end_game:
        post:
            operationId: endGame
            summary: 结束一盘五子棋游戏
            responses:
                "200":
                    description: 游戏成功结束
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/messageResponse"
    /step:
        post:
            operationId: step
            summary: 用户下这一步的坐标
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/step"
            responses:
                # 成功的返回，返回用户下一步后，AI再下一步后的棋盘
                "200":
                    description: 用户下一步后，AI再下一步后的棋盘。
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/stepResponse"
                # 失败的返回，只返回错误信息
                "400":
                    description: 返回错误信息
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/messageResponse"


    /read_board:
        post:
            operationId: readBoard
            summary: 从远程文件中读取棋盘
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/addBoard"
            responses:
                "200":
                    description: 远程文件中的棋盘读取成功
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/messageResponse"


components:
    schemas:
        step:
            type: object
            required: [ x, y ]
            properties:
                x:
                    type: integer
                    description: 棋盘上的横坐标
                y:
                    type: integer
                    description: 棋盘上的纵坐标

        stepResponse:
            type: object
            required: [ board ]
            properties:
                board:
                    type: array
                    items:
                        type: array
                        items:
                            type: string
                    description: 棋盘的二维数组，1代表黑子，2代表白子，0代表空。文心一言需要根据这个生成文字版棋盘。

        addBoard:
            type: object
            required: [ url ]
            properties:
                url:
                    type: string
                    description: 远程文件url地址，用<url><\url>包含

        messageResponse:
            type: object
            required: [message]
            properties:
                message:
                    type: string
                    description: 回复信息